development:
  host: localhost
  database: feast

test:
  host: localhost
  database: feast_test

# set these environment variables on your prod server
production:
  host: dbh35.mongolab.com
  port: 27357
  username: heroku_app747466
  password: om3nn1hemldclrasijtkjeib1
  database: feast
  # port: <%= ENV['MONGOID_PORT'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
