development:
  host: localhost
  database: feast

test:
  host: localhost
  database: feast_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOLAB_URI'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
